export type IconNames = 
  | "twitter-x"
  | "align-justify-1"
  | "align-justify"
  | "align-right"
  | "dismiss"
  | "facebook"
  | "globe"
  | "linkedin"
  | "mail"
  | "map-pin"
  | "minus1-1"
  | "phone"
  | "sound-on"
  | "twitter"
  | "logo-whatsapp"
  | "email"
  | "play"

